
package pl.kotcrab.arget.event;

public enum MenuEventType {
	FILE_LOGOUT, FILE_EXIT, //
	SERVERS_ADD, SERVERS_MANAGE, SERVERS_DISCONNECT, //
	CONTACTS_SHOW_PUBLIC_KEY, CONTACTS_ADD, CONTACTS_REFRESH, //
	VIEW_SHOW_HOME, VIEW_SHOW_LOG, //
	HELP_ABOUT //
}
